# DraCor API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 0.83.1
# Contact: fr.fischer@fu-berlin.de
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' CorporaCorpusnameBody Class
#'
#' @field load 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CorporaCorpusnameBody <- R6::R6Class(
  'CorporaCorpusnameBody',
  public = list(
    `load` = NULL,
    initialize = function(`load`){
      if (!missing(`load`)) {
        self$`load` <- `load`
      }
    },
    toJSON = function() {
      CorporaCorpusnameBodyObject <- list()
      if (!is.null(self$`load`)) {
        CorporaCorpusnameBodyObject[['load']] <- self$`load`
      }

      CorporaCorpusnameBodyObject
    },
    fromJSON = function(CorporaCorpusnameBodyJson) {
      CorporaCorpusnameBodyObject <- jsonlite::fromJSON(CorporaCorpusnameBodyJson)
      if (!is.null(CorporaCorpusnameBodyObject$`load`)) {
        self$`load` <- CorporaCorpusnameBodyObject$`load`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "load": %s
        }',
        self$`load`
      )
    },
    fromJSONString = function(CorporaCorpusnameBodyJson) {
      CorporaCorpusnameBodyObject <- jsonlite::fromJSON(CorporaCorpusnameBodyJson)
      self$`load` <- CorporaCorpusnameBodyObject$`load`
    }
  )
)
