# DraCor API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 0.83.1
# Contact: fr.fischer@fu-berlin.de
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' InlineResponse2001 Class
#'
#' @field id 
#' @field label 
#' @field isGroup 
#' @field gender 
#' @field text 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2001 <- R6::R6Class(
  'InlineResponse2001',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `isGroup` = NULL,
    `gender` = NULL,
    `text` = NULL,
    initialize = function(`id`, `label`, `isGroup`, `gender`, `text`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`isGroup`)) {
        self$`isGroup` <- `isGroup`
      }
      if (!missing(`gender`)) {
        stopifnot(is.character(`gender`), length(`gender`) == 1)
        self$`gender` <- `gender`
      }
      if (!missing(`text`)) {
        stopifnot(is.list(`text`), length(`text`) != 0)
        lapply(`text`, function(x) stopifnot(is.character(x)))
        self$`text` <- `text`
      }
    },
    toJSON = function() {
      InlineResponse2001Object <- list()
      if (!is.null(self$`id`)) {
        InlineResponse2001Object[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        InlineResponse2001Object[['label']] <- self$`label`
      }
      if (!is.null(self$`isGroup`)) {
        InlineResponse2001Object[['isGroup']] <- self$`isGroup`
      }
      if (!is.null(self$`gender`)) {
        InlineResponse2001Object[['gender']] <- self$`gender`
      }
      if (!is.null(self$`text`)) {
        InlineResponse2001Object[['text']] <- self$`text`
      }

      InlineResponse2001Object
    },
    fromJSON = function(InlineResponse2001Json) {
      InlineResponse2001Object <- jsonlite::fromJSON(InlineResponse2001Json)
      if (!is.null(InlineResponse2001Object$`id`)) {
        self$`id` <- InlineResponse2001Object$`id`
      }
      if (!is.null(InlineResponse2001Object$`label`)) {
        self$`label` <- InlineResponse2001Object$`label`
      }
      if (!is.null(InlineResponse2001Object$`isGroup`)) {
        self$`isGroup` <- InlineResponse2001Object$`isGroup`
      }
      if (!is.null(InlineResponse2001Object$`gender`)) {
        self$`gender` <- InlineResponse2001Object$`gender`
      }
      if (!is.null(InlineResponse2001Object$`text`)) {
        self$`text` <- InlineResponse2001Object$`text`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "isGroup": %s,
           "gender": %s,
           "text": [%s]
        }',
        self$`id`,
        self$`label`,
        self$`isGroup`,
        self$`gender`,
        lapply(self$`text`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(InlineResponse2001Json) {
      InlineResponse2001Object <- jsonlite::fromJSON(InlineResponse2001Json)
      self$`id` <- InlineResponse2001Object$`id`
      self$`label` <- InlineResponse2001Object$`label`
      self$`isGroup` <- InlineResponse2001Object$`isGroup`
      self$`gender` <- InlineResponse2001Object$`gender`
      self$`text` <- InlineResponse2001Object$`text`
    }
  )
)
