# DraCor API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 0.83.1
# Contact: fr.fischer@fu-berlin.de
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' InlineResponse2002 Class
#'
#' @field id 
#' @field uri 
#' @field title 
#' @field authors 
#' @field characterName 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2002 <- R6::R6Class(
  'InlineResponse2002',
  public = list(
    `id` = NULL,
    `uri` = NULL,
    `title` = NULL,
    `authors` = NULL,
    `characterName` = NULL,
    initialize = function(`id`, `uri`, `title`, `authors`, `characterName`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`authors`)) {
        stopifnot(is.list(`authors`), length(`authors`) != 0)
        lapply(`authors`, function(x) stopifnot(is.character(x)))
        self$`authors` <- `authors`
      }
      if (!missing(`characterName`)) {
        stopifnot(is.character(`characterName`), length(`characterName`) == 1)
        self$`characterName` <- `characterName`
      }
    },
    toJSON = function() {
      InlineResponse2002Object <- list()
      if (!is.null(self$`id`)) {
        InlineResponse2002Object[['id']] <- self$`id`
      }
      if (!is.null(self$`uri`)) {
        InlineResponse2002Object[['uri']] <- self$`uri`
      }
      if (!is.null(self$`title`)) {
        InlineResponse2002Object[['title']] <- self$`title`
      }
      if (!is.null(self$`authors`)) {
        InlineResponse2002Object[['authors']] <- self$`authors`
      }
      if (!is.null(self$`characterName`)) {
        InlineResponse2002Object[['characterName']] <- self$`characterName`
      }

      InlineResponse2002Object
    },
    fromJSON = function(InlineResponse2002Json) {
      InlineResponse2002Object <- jsonlite::fromJSON(InlineResponse2002Json)
      if (!is.null(InlineResponse2002Object$`id`)) {
        self$`id` <- InlineResponse2002Object$`id`
      }
      if (!is.null(InlineResponse2002Object$`uri`)) {
        self$`uri` <- InlineResponse2002Object$`uri`
      }
      if (!is.null(InlineResponse2002Object$`title`)) {
        self$`title` <- InlineResponse2002Object$`title`
      }
      if (!is.null(InlineResponse2002Object$`authors`)) {
        self$`authors` <- InlineResponse2002Object$`authors`
      }
      if (!is.null(InlineResponse2002Object$`characterName`)) {
        self$`characterName` <- InlineResponse2002Object$`characterName`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "uri": %s,
           "title": %s,
           "authors": [%s],
           "characterName": %s
        }',
        self$`id`,
        self$`uri`,
        self$`title`,
        lapply(self$`authors`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`characterName`
      )
    },
    fromJSONString = function(InlineResponse2002Json) {
      InlineResponse2002Object <- jsonlite::fromJSON(InlineResponse2002Json)
      self$`id` <- InlineResponse2002Object$`id`
      self$`uri` <- InlineResponse2002Object$`uri`
      self$`title` <- InlineResponse2002Object$`title`
      self$`authors` <- InlineResponse2002Object$`authors`
      self$`characterName` <- InlineResponse2002Object$`characterName`
    }
  )
)
