# DraCor API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 0.83.1
# Contact: fr.fischer@fu-berlin.de
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' InlineResponse200 Class
#'
#' @field title 
#' @field dramas 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse200 <- R6::R6Class(
  'InlineResponse200',
  public = list(
    `title` = NULL,
    `dramas` = NULL,
    initialize = function(`title`, `dramas`){
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`dramas`)) {
        stopifnot(is.list(`dramas`), length(`dramas`) != 0)
        lapply(`dramas`, function(x) stopifnot(R6::is.R6(x)))
        self$`dramas` <- `dramas`
      }
    },
    toJSON = function() {
      InlineResponse200Object <- list()
      if (!is.null(self$`title`)) {
        InlineResponse200Object[['title']] <- self$`title`
      }
      if (!is.null(self$`dramas`)) {
        InlineResponse200Object[['dramas']] <- lapply(self$`dramas`, function(x) x$toJSON())
      }

      InlineResponse200Object
    },
    fromJSON = function(InlineResponse200Json) {
      InlineResponse200Object <- jsonlite::fromJSON(InlineResponse200Json)
      if (!is.null(InlineResponse200Object$`title`)) {
        self$`title` <- InlineResponse200Object$`title`
      }
      if (!is.null(InlineResponse200Object$`dramas`)) {
        self$`dramas` <- lapply(InlineResponse200Object$`dramas`, function(x) {
          dramasObject <- TODO_OBJECT_MAPPING$new()
          dramasObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          dramasObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "title": %s,
           "dramas": [%s]
        }',
        self$`title`,
        lapply(self$`dramas`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(InlineResponse200Json) {
      InlineResponse200Object <- jsonlite::fromJSON(InlineResponse200Json)
      self$`title` <- InlineResponse200Object$`title`
      self$`dramas` <- lapply(InlineResponse200Object$`dramas`, function(x) TODO_OBJECT_MAPPING$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
