# DraCor API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 0.83.1
# Contact: fr.fischer@fu-berlin.de
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#' @title Public operations
#' @description swagger.Public
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' api_info API info
#'
#'
#' corpus_metadata List of metadata for all plays in a corpus
#'
#'
#' corpus_metadata_csv List of metadata for all plays in a corpus
#'
#'
#' corpus_metadata_csv_endpoint List of metadata for all plays in a corpus
#'
#'
#' get_cast Get a list of characters of a play
#'
#'
#' get_cast_csv Get a list of characters of a play (CSV)
#'
#'
#' list_corpora List available corpora
#'
#'
#' list_corpus_content List corpus content
#'
#'
#' network_csv Get network data of a play as CSV
#'
#'
#' network_gexf Get network data of a play as GEXF
#'
#'
#' network_graphml Get network data of a play as GraphML
#'
#'
#' play_info Get metadata and network metrics for a single play
#'
#'
#' play_metrics Get network metrics for a single play
#'
#'
#' play_rdf Get RDF document for a single play
#'
#'
#' play_segments_xml Get a list of segments and characters of a play
#'
#'
#' play_spoken_text Get spoken text of a play (excluding stage directions)
#'
#'
#' play_spoken_text_by_character Get spoken text for each character of a play
#'
#'
#' play_stage_directions Get all stage directions of a play
#'
#'
#' play_stage_directions_with_speakers Get all stage directions of a play including speakers
#'
#'
#' play_tei Get TEI document of a single play
#'
#'
#' plays_with_character List plays having a character identified by Wikidata ID
#'
#'
#' relations_csv Get relation data of a play as CSV
#'
#'
#' relations_gexf Get relation data of a play as GEXF
#'
#'
#' relations_graphml Get relation data of a play as GraphML
#'
#'
#' resolve_id Resolve DraCor play ID
#'
#' }
#'
#' @export
PublicApi <- R6::R6Class(
  'PublicApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    api_info = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/info"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    corpus_metadata = function(corpusname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/metadata"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- TODO_OBJECT_MAPPING$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    corpus_metadata_csv = function(corpusname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/metadata.csv"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    corpus_metadata_csv_endpoint = function(corpusname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/metadata/csv"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    get_cast = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/cast"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- TODO_OBJECT_MAPPING$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    get_cast_csv = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/cast/csv"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    list_corpora = function(include, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include`)) {
        queryParams['include'] <- include
      }

      urlPath <- "/corpora"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- TODO_OBJECT_MAPPING$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    list_corpus_content = function(corpusname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- InlineResponse200$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    network_csv = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/networkdata/csv"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    network_gexf = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/networkdata/gexf"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    network_graphml = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/networkdata/graphml"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_info = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- TODO_OBJECT_MAPPING$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_metrics = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/metrics"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- TODO_OBJECT_MAPPING$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_rdf = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/rdf"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_segments_xml = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/segmentation"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_spoken_text = function(corpusname, playname, gender, relation, role, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`gender`)) {
        queryParams['gender'] <- gender
      }

      if (!missing(`relation`)) {
        queryParams['relation'] <- relation
      }

      if (!missing(`role`)) {
        queryParams['role'] <- role
      }

      urlPath <- "/corpora/{corpusname}/play/{playname}/spoken-text"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_spoken_text_by_character = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/spoken-text-by-character"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- InlineResponse2001$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_stage_directions = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/stage-directions"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_stage_directions_with_speakers = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/stage-directions-with-speakers"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    play_tei = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/tei"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    plays_with_character = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/character/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), `id`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- InlineResponse2002$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    relations_csv = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/relations/csv"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    relations_gexf = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/relations/gexf"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    relations_graphml = function(corpusname, playname, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/corpora/{corpusname}/play/{playname}/relations/graphml"
      if (!missing(`corpusname`)) {
        urlPath <- gsub(paste0("\\{", "corpusname", "\\}"), `corpusname`, urlPath)
      }

      if (!missing(`playname`)) {
        urlPath <- gsub(paste0("\\{", "playname", "\\}"), `playname`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Character$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
    resolve_id = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/id/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), `id`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
